# Generated by Django 4.1.3 on 2022-11-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=15, null=True)),
                ("title", models.CharField(blank=True, max_length=25, null=True)),
                ("des", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
