# Generated by Django 4.1.3 on 2022-11-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="")),
                ("title", models.CharField(blank=True, max_length=15, null=True)),
                ("des", models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
