# Generated by Django 4.1.3 on 2022-11-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_alter_about_des"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="img",
        ),
    ]
