# Generated by Django 4.1.3 on 2022-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0008_alter_about_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("des", models.CharField(blank=True, max_length=20, null=True)),
                ("Icon1", models.CharField(blank=True, max_length=30, null=True)),
                ("Icon2", models.CharField(blank=True, max_length=30, null=True)),
                ("Icon3", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
