# Generated by Django 4.1.3 on 2022-11-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0009_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="img",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="about",
            name="sub_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
