# Generated by Django 4.1.3 on 2022-11-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0011_client"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Footer",
        ),
    ]
