# Generated by Django 4.1.3 on 2022-11-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0012_rename_client_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_link", models.ImageField(upload_to="")),
            ],
        ),
    ]
