# Generated by Django 4.1.3 on 2022-11-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0013_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="img_link",
            field=models.ImageField(upload_to=True),
        ),
    ]
