# Generated by Django 4.1.3 on 2022-11-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0016_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="mess",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
